version: '3.9'

services:
#  go-dev:
#    image: cosmtrek/air
#    volumes:
#    - .:/go/src/github.com/djboboch/go-todo
#    ports:
#    - 8000:8000
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
    - /data/database/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=golang
      - POSTGRES_PASSWORD=password
