version: '3.9'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
    - /data/database/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=golang
      - POSTGRES_PASSWORD=password
