version: '3.9'

services:
  go:
    build: .
    ports:
    - 8000:8000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=golang
      - DB_PASSWORD=password
      - DB_NAME=testdb
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
    - /data/database/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=golang
      - POSTGRES_PASSWORD=password
